# Definitions:

In [ ]:
NumPy is a Python library used for working with arrays.

NumPy stands for Numerical Python.

# Numpy Functions

# 1. Array:

In [ ]:
It is used to create one-dimensional or multidimensional arrays from scratch.

In [1]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

# 2. Linspace:

In [ ]:
Creates an array with evenly spaced float numbers over a specified interval.

In [2]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# 3. Arange:

In [3]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [4]:
np.arange(5,10,2)
#(starting point,ending point,steps point)

array([5, 7, 9])

# 4. Random.randint:

In [ ]:
Generate n random integer samples within a range.

In [6]:
np.random.randint(5,10,10)

array([8, 9, 8, 9, 9, 6, 5, 7, 8, 7])

# 5. Random.random:

In [ ]:
Generate n random float samples.

In [7]:
np.random.random(3)

array([0.73512966, 0.22030493, 0.28214624])

# 6. Logspace:

In [ ]:
Generate evenly spaced numbers on a log scale.

In [8]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

# 7. Array of zero:

In [ ]:
np.zeroes function helps to create an array of 0

In [12]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

# 8. Array of Ones:

In [ ]:
np.ones function helps to create an array of 1.

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 9. Array of k Random Value:

In [ ]:
Creates an n-dimensional array of a random value.
fill_value: Random value to fill inside the array.

In [14]:
np.full((2,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [15]:
np.full((4,6),fill_value=9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

# -- Array Operations --

# Min:

In [ ]:
Return the minimum value from the array.

In [16]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.min(arr)

1

## Max:

In [ ]:
Return the maximum value from the array.

In [17]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.max(arr)

6

# Unique:

In [ ]:
Return an array with all the unique elements sorted.

In [21]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])

np.unique(arr,return_index=True,return_counts=True,axis=None)

(array([1, 2, 3, 4, 5, 6]),
 array([0, 2, 3, 5, 6, 7], dtype=int64),
 array([2, 2, 2, 1, 1, 2], dtype=int64))

# Mean:

In [ ]:
It is used to get the mean of the array.

In [23]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.mean(arr,dtype='int')

3

# Median:

In [ ]:
Return the median value of the array.

In [24]:
arr = np.array([[1,2,3],[5,8,4]])
np.median(arr)

3.5

# Reshape:

In [ ]:
It is one of the most used functions of NumPy. It Returns an array containing the 
same data with a new shape.

In [29]:
A = np.random.randint(15,size=(4,3))
A

array([[12, 10,  7],
       [14,  1, 11],
       [ 1,  5, 11],
       [ 8, 12,  2]])

In [27]:
A = np.random.randint(18,size=(6,5))
A

array([[ 3, 17,  6, 11,  9],
       [16,  0,  6, 17,  6],
       [ 6, 13, 17,  9, 13],
       [16,  6, 14, 14, 14],
       [15, 16,  6,  3,  7],
       [17,  7, 13, 12,  5]])

In [30]:
A.reshape(3,4)

array([[12, 10,  7, 14],
       [ 1, 11,  1,  5],
       [11,  8, 12,  2]])

# Squeeze:

In [ ]:
Reduce the dimension of an array by removing single-dimensional entrie.

In [31]:
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

In [33]:
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
arr

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [ 1],
       [13],
       [13],
       [11]])

# Count Non-Zero:

In [ ]:
Count all the non-zero elements and return their count.

In [35]:
a = np.array([0,0,1,1,1,0,5,7])
np.count_nonzero(a)

5

# argwhere:

In [ ]:
Find and return all the indices of non-zero elements.

In [36]:
a = np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]], dtype=int64)

# argmax:

In [ ]:
argmax returns the index of the max element from the array.

In [37]:
arr = np.array([[0.12,0.64,0.19,0.05]])
np.argmax(arr)

1

# argmin:

In [ ]:
argmin will return the index of the lowest element from the array.

In [40]:
arr = np.array([[0.12,0.64,0.19,0.05]])
np.argmin(arr)

3

# Sort:

In [ ]:
Sort the array and return.

In [41]:
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

# Abs:

In [ ]:
Return the absolute values of elements inside an array. It is useful 
when an array contains negative values.

In [42]:
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

In [43]:
b=np.array([-8,9,2,5,-4,-6,-56,-8,-3])
np.abs(b)

array([ 8,  9,  2,  5,  4,  6, 56,  8,  3])

# Round

In [ ]:
Round the float values to a specified number of decimal points.

decimals: Number of decimals point to keep.

In [44]:
a = np.random.random(size=(3,4))
a

array([[0.79001881, 0.49891383, 0.62879553, 0.94258639],
       [0.1841263 , 0.51911255, 0.91157893, 0.60257206],
       [0.4258092 , 0.74668997, 0.49866824, 0.63414114]])

In [45]:
np.round(a,decimals=0)

array([[1., 0., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 0., 1.]])

In [46]:
np.round(a,decimals=1)

array([[0.8, 0.5, 0.6, 0.9],
       [0.2, 0.5, 0.9, 0.6],
       [0.4, 0.7, 0.5, 0.6]])

# Clip:

In [ ]:
It is used to keep the values of an array within a range.

In [47]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [48]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [49]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

# Where:

In [50]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

# Union:

In [ ]:
union function will combine both arrays into one.

In [53]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

# -- Splitting --

# Horizontal Split:

In [ ]:
hsplit function will split the data horizontally into n equal parts.

In [54]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,2)
## splits the data into two equal parts

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [55]:
np.hsplit(A,4)    ## splits the data into four equal parts

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

# Vertical Split:

In [ ]:
vsplit will split the data vertically into n equal parts.

In [56]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

# -- Stacking --

# Horizontal Stacking:

In [ ]:
hstack will stack appends one array at the end of another.

In [57]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

# Vertical Stacking:

In [ ]:
vstack will stack one array on top of another.

In [59]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

# Repeat:

In [ ]:
It is used to repeat elements of an array for n number of times.

In [60]:
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

In [61]:
import pandas as pd

In [62]:
fruits = pd.DataFrame([
    ['Mango',40],
    ['Apple',90],
    ['Banana',130]
],columns=['Product','ContainerSales'])
fruits

Product  ContainerSales
0   Mango              40
1   Apple              90
2  Banana             130

In [63]:
# In the dataset, the year column is missing. Let’s try to add it using numpy.
fruits['year'] = np.repeat(2020,fruits.shape[0])
fruits

Product  ContainerSales  year
0   Mango              40  2020
1   Apple              90  2020
2  Banana             130  2020

# Save:

In [ ]:
savetxt used to save the content of an array inside a text file.

In [64]:
''' Generate array with 500 elements '''

arr = np.linspace(10,100,500).reshape(25,20) 

##◾ 𝗦𝗮𝘃𝗲𝘀 𝗔𝗿𝗿𝗮𝘆 𝗗𝗮𝘁𝗮 𝗜𝗻𝘀𝗶𝗱𝗲 𝗮 𝘁𝘅𝘁 𝗙𝗶𝗹𝗲
np.savetxt('array.txt',arr)

# Load:

In [ ]:
loadtxt used to load the content of an array from a text file. It takes the 
file name as a parameter.

In [65]:
np.loadtxt('array.txt')

array([[ 10.        ,  10.18036072,  10.36072144,  10.54108216,
         10.72144289,  10.90180361,  11.08216433,  11.26252505,
         11.44288577,  11.62324649,  11.80360721,  11.98396794,
         12.16432866,  12.34468938,  12.5250501 ,  12.70541082,
         12.88577154,  13.06613226,  13.24649299,  13.42685371],
       [ 13.60721443,  13.78757515,  13.96793587,  14.14829659,
         14.32865731,  14.50901804,  14.68937876,  14.86973948,
         15.0501002 ,  15.23046092,  15.41082164,  15.59118236,
         15.77154309,  15.95190381,  16.13226453,  16.31262525,
         16.49298597,  16.67334669,  16.85370741,  17.03406814],
       [ 17.21442886,  17.39478958,  17.5751503 ,  17.75551102,
         17.93587174,  18.11623246,  18.29659319,  18.47695391,
         18.65731463,  18.83767535,  19.01803607,  19.19839679,
         19.37875752,  19.55911824,  19.73947896,  19.91983968,
         20.1002004 ,  20.28056112,  20.46092184,  20.64128257],
       [ 20.82164329,  21.00200401,  

# Thanks For Reading
I hope You Found Someting useful.